import { type NodeDoc, Topic } from "../../doc.ts";

export const doc: NodeDoc = {
  title: "Form 1040 header",
  subtitle: "Filer information, filing status and dependents",
  topic: Topic.Household,
  summary:
    "The basic facts at the top of Form 1040: your filing status, names, SSNs, address, and the dependents you claim. " +
    "Every return needs it. Filing status sets the tax brackets, standard deduction and many phase-out thresholds; age 65 and blindness raise the standard deduction; " +
    "and the dependent list decides the Child Tax Credit and credit for other dependents (Schedule 8812) and the number of children for the Earned Income Credit.",
  fields: {
    filing_status: "Your filing status for the year (Form 1040 checkboxes). Drives brackets, the standard deduction and many credit and surtax thresholds.",
    taxpayer_first_name: "Your first name as shown on your Social Security card.",
    taxpayer_last_name: "Your last name.",
    taxpayer_middle_initial: "Your middle initial, one letter.",
    taxpayer_suffix: "Name suffix, such as Jr. or III.",
    taxpayer_ssn: "Your Social Security number. Without one, some benefits (such as the Schedule 1-A deductions) are not allowed.",
    taxpayer_dob: "Your date of birth (YYYY-MM-DD). If the 65-or-older box is left blank, the engine uses this to decide whether you were 65 by the end of the year.",
    taxpayer_blind: "Mark if you were legally blind at the end of the year. Adds to your standard deduction.",
    taxpayer_age_65_or_older: "Mark if you were 65 or older at the end of the year (born before January 2, 1961). Adds to your standard deduction.",
    taxpayer_occupation: "Your occupation, printed by the signature line.",
    taxpayer_daytime_phone: "Daytime phone number, printed by the signature line.",
    taxpayer_email: "Your email address.",
    taxpayer_deceased: "Mark if you died during the year or before the return was filed.",
    taxpayer_death_date: "Date of death (YYYY-MM-DD), if deceased.",
    taxpayer_ip_pin: "The six-digit Identity Protection PIN the IRS issued you, if any. Required on the return when you have one.",
    taxpayer_prior_year_agi: "Last year's adjusted gross income, used to verify your identity when you sign an e-filed return.",
    spouse_first_name: "Your spouse's first name (joint or separate returns).",
    spouse_last_name: "Your spouse's last name.",
    spouse_middle_initial: "Your spouse's middle initial.",
    spouse_suffix: "Your spouse's name suffix, if any.",
    spouse_ssn: "Your spouse's Social Security number. On a separate return it is listed next to the filing status.",
    spouse_dob: "Your spouse's date of birth (YYYY-MM-DD). Used to decide 65-or-older status when that box is blank.",
    spouse_blind: "Mark if your spouse was legally blind at the end of the year. Adds to the standard deduction.",
    spouse_age_65_or_older: "Mark if your spouse was 65 or older at the end of the year. Adds to the standard deduction.",
    spouse_occupation: "Your spouse's occupation.",
    spouse_daytime_phone: "Your spouse's daytime phone number.",
    spouse_email: "Your spouse's email address.",
    spouse_deceased: "Mark if your spouse died during the year or before the return was filed.",
    spouse_death_date: "Spouse's date of death (YYYY-MM-DD), if deceased.",
    spouse_ip_pin: "Your spouse's six-digit Identity Protection PIN, if the IRS issued one.",
    spouse_prior_year_agi: "Your spouse's prior-year AGI, used to verify identity when signing an e-filed return.",
    address_line1: "Street address, or P.O. box if mail is not delivered to your street.",
    address_line2: "Apartment or unit number.",
    address_in_care_of: "\"In care of\" name, if mail goes to someone else's address.",
    address_city: "City, town or post office.",
    address_state: "State, as a two-letter code.",
    address_zip: "ZIP code.",
    address_foreign_country: "Country name, if your address is outside the United States.",
    address_foreign_province_state: "Foreign province, state or county.",
    address_foreign_postal_code: "Foreign postal code.",
    digital_assets: "The digital asset question at the top of Form 1040: did you receive, sell, exchange or otherwise dispose of any digital asset during the year?",
    presidential_campaign_fund_taxpayer: "Mark to direct $3 to the Presidential Election Campaign Fund. Does not change your tax or refund.",
    presidential_campaign_fund_spouse: "Mark if your spouse wants $3 to go to the Presidential Election Campaign Fund (joint returns).",
    extension_filed: "Mark if you filed Form 4868 to extend the filing deadline.",
    taxpayer_signature_pin: "The five-digit self-select PIN you use to sign an e-filed return.",
    spouse_signature_pin: "Your spouse's five-digit self-select PIN for signing an e-filed return.",
    mfs_spouse_itemizing: "Married filing separately only: mark if your spouse itemizes deductions. You must then itemize too; your standard deduction is zero.",
    mfs_spouse_lived_with_taxpayer: "Married filing separately only: whether you lived with your spouse at any time during the year. This affects rules such as Social Security taxability.",
    hoh_qualifying_person_name: "Head of household only: the qualifying person's name, when that person is a child who is not your dependent.",
    hoh_qualifying_person_relationship: "Head of household only: your relationship to the qualifying person.",
    hoh_paid_more_than_half_home_costs: "Head of household only: whether you paid more than half the cost of keeping up your home for the year, a requirement for that status.",
    qss_spouse_death_year: "Qualifying surviving spouse only: the year your spouse died. This status is available for the two years after the year of death.",
    qss_qualifying_child_ssn: "Qualifying surviving spouse only: the SSN of the dependent child who lived with you.",
    bank_routing_number: "Nine-digit routing number for direct deposit of your refund (Form 1040 line 35b).",
    bank_account_number: "Account number for direct deposit of your refund (line 35d).",
    bank_account_type: "Whether the direct deposit account is checking or savings (line 35c).",
    dependents: "The people you claim as dependents, one row each (Form 1040 Dependents section).",
    "dependents.first_name": "Dependent's first name.",
    "dependents.last_name": "Dependent's last name.",
    "dependents.middle_initial": "Dependent's middle initial.",
    "dependents.ssn": "Dependent's Social Security number. A child needs one valid for work for the Child Tax Credit.",
    "dependents.itin": "Dependent's Individual Taxpayer Identification Number, if they have no SSN. Allows the credit for other dependents but not the Child Tax Credit.",
    "dependents.atin": "Adoption Taxpayer Identification Number, for a child being adopted who has no SSN yet. Allows the credit for other dependents but not the Child Tax Credit.",
    "dependents.dob": "Dependent's date of birth (YYYY-MM-DD). The engine uses age at December 31 for the under-17 Child Tax Credit test and the under-19 (or student under 24) qualifying child test.",
    "dependents.relationship": "The dependent's relationship to you. Decides whether they can be a qualifying child or only a qualifying relative.",
    "dependents.months_in_home": "Months the dependent lived with you during the year. More than six are needed to be a qualifying child.",
    "dependents.qualifying_child_for_ctc": "Override: mark yes or no to set Child Tax Credit eligibility directly instead of letting the engine apply the tests.",
    "dependents.disabled": "Mark if the dependent was permanently and totally disabled. Removes the age limits.",
    "dependents.full_time_student": "Mark if the dependent was a full-time student. Extends qualifying child status to under 24 (but not the Child Tax Credit).",
    "dependents.gross_income": "The dependent's gross income. For a qualifying relative it must be under $5,050 for 2025.",
    "dependents.taxpayer_provided_over_half_support": "Whether you provided more than half of this person's support. Setting it to no rules them out as a qualifying relative.",
    "dependents.dependent_on_another_return": "Mark if someone else claims this person. They are then left out of all your dependent counts.",
    "dependents.child_care_months": "Months of the year you paid for this dependent's care, for Form 2441.",
    "dependents.education_credit_eligible": "Mark if this dependent had qualified education expenses for an education credit (Form 8863).",
    "dependents.ip_pin": "The dependent's six-digit Identity Protection PIN, if the IRS issued one.",
  },
  options: {
    filing_status: {
      single: "Single: unmarried or legally separated at the end of the year, with no other status that applies.",
      mfs: "Married filing separately: married, each spouse files their own return.",
      mfj: "Married filing jointly: married couple combining income and deductions on one return.",
      hoh: "Head of household: unmarried and paid more than half the cost of a home for a qualifying person.",
      qss: "Qualifying surviving spouse: spouse died in one of the two prior years and you keep a home for a dependent child.",
    },
    "dependents.relationship": {
      son: "Your son.",
      daughter: "Your daughter.",
      stepchild: "Your stepson or stepdaughter.",
      foster: "A foster child placed with you by an authorized agency or court.",
      sibling: "Your brother or sister.",
      stepsibling: "Your stepbrother or stepsister.",
      halfsibling: "Your half brother or half sister.",
      grandchild: "Your grandchild (or other descendant of your child).",
      parent: "Your mother or father. Can only be a qualifying relative.",
      stepparent: "Your stepmother or stepfather. Can only be a qualifying relative.",
      sibling_parent: "Your aunt or uncle (a sibling of your parent). Can only be a qualifying relative.",
      child_sibling: "Your niece or nephew (a child of your sibling).",
      other: "Any other relative or member of your household. Can only be a qualifying relative.",
    },
  },
};
