import { type NodeDoc, Topic } from "../../doc.ts";

export const doc: NodeDoc = {
  title: "Schedule C",
  subtitle: "Profit or Loss From Business (Sole Proprietorship)",
  topic: Topic.Business,
  summary:
    "The schedule a sole proprietor or single-member LLC owner files to report a business's income, cost of goods sold and expenses. " +
    "File one per business. The combined net profit or loss goes to Schedule 1 line 3 and on to Form 1040 line 8; a combined profit of $400 or more " +
    "(less for clergy) triggers self-employment tax on Schedule SE, and profit also counts as qualified business income for Form 8995 " +
    "and as earned income for the EITC and child tax credit. Losses can be limited by the passive activity, at-risk and excess business loss rules.",
  fields: {
    line_a_principal_business: "Line A. The general field or activity your business income comes from, such as \"residential painting\" or \"online retail of clothing\".",
    line_b_business_code: "Line B. The six-digit principal business activity code from the list in the Schedule C instructions.",
    line_c_business_name: "Line C. The business name, if different from your own name. Leave blank if you operate under your personal name.",
    line_d_ein: "Line D. The business's employer identification number, if it has one (for example because it has employees or a retirement plan).",
    line_e_business_address: "Line E. The street address of the business, if different from the home address on your Form 1040.",
    line_f_accounting_method: "Line F. The accounting method you use for this business.",
    line_g_material_participation: "Line G. Whether you materially participated in the business this year. If not, the engine treats the profit or loss as passive and sends it to Form 8582.",
    line_h_new_business: "Line H. Check if you started or acquired this business during the year.",
    line_i_made_1099_payments: "Line I. Whether you made payments during the year that require you to file Forms 1099, such as payments to contractors.",
    line_j_filed_1099s: "Line J. If line I is yes, whether you filed or will file all the required Forms 1099.",
    statutory_employee: "Check if this income was reported on a W-2 with the statutory employee box checked. The employer already withheld Social Security and Medicare tax, so the engine leaves this business out of Schedule SE.",
    exempt_notary: "Check if all of this business's income is notary public fees, which are not subject to self-employment tax. The engine leaves it out of Schedule SE.",
    paper_route: "Check if you are under 18 and this income is from delivering newspapers, which is exempt from self-employment tax. The engine leaves it out of Schedule SE.",
    professional_gambler: "Check if you gamble as a trade or business. Gambling losses can't create a net loss, so the engine limits this business's net profit to no less than zero.",
    clergy_schedule_c: "Check if this Schedule C belongs to a member of the clergy. The engine then uses the lower $108.28 threshold for filing Schedule SE.",
    disposed_of_business: "Check if you closed or disposed of this business during the year. It is a record-keeping flag and does not change this year's tax.",
    multi_form_code: "An optional label that distinguishes this business from your other Schedule C businesses when routing entries. It has no tax effect.",
    llc_number: "An optional number (1 to 999) tying this business to a single-member LLC for state filings. It has no federal tax effect.",
    subject_to_163j: "Check if the business is subject to the business interest expense limit of section 163(j). The engine sends the line 16a and 16b interest to Form 8990.",
    qbi_specified_service: "Check if this is a specified service trade or business (such as health, law, accounting, consulting or financial services) for the qualified business income deduction. It matters once taxable income is above the QBI threshold.",
    qbi_w2_wages: "W-2 wages the business paid to employees, used for the wage limit on the qualified business income deduction at higher incomes.",
    qbi_unadjusted_basis: "The unadjusted basis immediately after acquisition (UBIA) of the business's qualified property, used with W-2 wages for the QBI deduction limit at higher incomes.",
    line_1_gross_receipts: "Line 1. Gross receipts or sales from the business, including amounts reported to you on Forms 1099-NEC, 1099-MISC and 1099-K.",
    line_2_returns_allowances: "Line 2. Refunds, returns and allowances you gave customers. Subtracted from line 1.",
    line_6_other_income: "Line 6. Other business income not included on line 1, such as scrap sales, recovered bad debts or fuel tax credits and refunds. Can be negative.",
    line_8_advertising: "Line 8. Advertising costs.",
    line_9_car_truck_expenses: "Line 9. Car and truck expenses, using either the standard mileage rate or actual costs. Amounts from the vehicle expense worksheet are added here.",
    line_10_commissions_fees: "Line 10. Commissions and fees paid to others for services.",
    line_11_contract_labor: "Line 11. Payments to independent contractors (not employees).",
    line_12_depletion: "Line 12. Depletion of natural resources such as timber, minerals or oil and gas. The engine also reports it to Form 6251 as an alternative minimum tax adjustment.",
    line_13_depreciation: "Line 13. Depreciation and section 179 expense, normally figured on Form 4562.",
    line_14_employee_benefits: "Line 14. Employee benefit programs, such as health and life insurance for employees (not for yourself, and not retirement plans).",
    line_15_insurance: "Line 15. Business insurance, other than health insurance for yourself.",
    line_16a_interest_mortgage: "Line 16a. Mortgage interest paid to banks and others (reported on Form 1098) on business property.",
    line_16b_interest_other: "Line 16b. Other business interest, such as on business loans or credit cards.",
    line_17_professional_services: "Line 17. Legal and professional fees, such as accountants and attorneys.",
    line_18_office_expense: "Line 18. Office expenses, such as postage and office supplies.",
    line_19_pension_plans: "Line 19. Contributions to retirement plans for your employees. Contributions for yourself go on Schedule 1 instead.",
    line_20a_rent_vehicles: "Line 20a. Rent or lease payments for vehicles, machinery and equipment.",
    line_20b_rent_other: "Line 20b. Rent for other business property, such as an office or store.",
    line_21_repairs: "Line 21. Repairs and maintenance of business property.",
    line_22_supplies: "Line 22. Supplies not included in cost of goods sold.",
    line_23_taxes_licenses: "Line 23. Business taxes and licenses, such as the employer share of payroll taxes and business license fees.",
    line_24a_travel: "Line 24a. Business travel expenses, such as airfare and lodging.",
    line_24b_meals: "Line 24b. The full amount you spent on business meals. The engine deducts 50% of it, or a higher share if one of the two flags below applies.",
    meals_dot_worker: "Check if the meals were eaten while you were subject to Department of Transportation hours-of-service rules. The engine then deducts 80% of line 24b.",
    meals_as_wages: "Check if the meals were treated as taxable compensation to employees. The engine then deducts 100% of line 24b.",
    line_25_utilities: "Line 25. Utilities for business property, such as electricity, water and phone.",
    line_26_wages: "Line 26. Wages paid to employees, less any employment credits. Don't include amounts paid to yourself.",
    line_27a_energy_efficient: "Line 27a. The energy efficient commercial buildings deduction (section 179D), figured on Form 7205.",
    line_27b_other_expenses: "Line 27b. Total other expenses not listed above. The engine adds this and the Part V items, so don't enter the same expense in both places.",
    line_30_home_office: "Line 30. Expenses for business use of your home, such as the amount from Form 8829. The engine limits it so it can't create a loss.",
    home_office_sq_ft: "The square feet of your home used regularly and only for business, for the simplified method.",
    home_office_method: "How you figure the home office deduction.",
    line_32_at_risk: "Line 32. If the business has a loss, whether all of your investment in it is at risk.",
    line_33_inventory_method: "Line 33. The method used to value closing inventory.",
    line_34_inventory_change: "Line 34. Whether you changed how you determine inventory quantities, costs or values between opening and closing inventory.",
    line_35_cogs_beginning_inventory: "Line 35. Inventory at the start of the year. Should match last year's closing inventory.",
    line_36_purchases: "Line 36. Purchases of goods for sale, less any items withdrawn for personal use.",
    line_37_cost_of_labor: "Line 37. Labor costs that are part of making the product. Don't include amounts paid to yourself.",
    line_38_materials_supplies_cogs: "Line 38. Materials and supplies used in making the product.",
    line_39_other_cogs: "Line 39. Other costs of goods sold.",
    line_41_cogs_ending_inventory: "Line 41. Inventory at the end of the year. Subtracted to arrive at cost of goods sold, which reduces gross income.",
    line_43_date_in_service: "Line 43. The date you first placed your vehicle in service for business. Part IV is for your records; the engine does not compute with it.",
    line_44a_total_miles: "The total miles you drove the vehicle during the year (the starting figure for line 44).",
    line_44b_business_miles: "Line 44a. Of the total, the miles driven for business.",
    line_44c_commuting_miles: "Line 44b. Of the total, the miles driven commuting between home and your regular workplace, which are not deductible.",
    line_44d_other_miles: "Line 44c. Of the total, other personal miles.",
    line_45_personal_use: "Line 45. Whether the vehicle was available for personal use during off-duty hours.",
    line_46_another_vehicle: "Line 46. Whether you (or your spouse) had another vehicle available for personal use.",
    line_47a_evidence: "Line 47a. Whether you have evidence to support the deduction.",
    line_47b_written_evidence: "Line 47b. If line 47a is yes, whether that evidence is written.",
    part_v_other_expenses: "Part V. A list of other business expenses that don't fit on lines 8 through 26 or line 30. Each item is added to total expenses.",
    "part_v_other_expenses.description": "What the expense is, such as \"software subscriptions\".",
    "part_v_other_expenses.amount": "The amount of the expense.",
  },
  options: {
    line_f_accounting_method: {
      cash: "Cash: income counts when received and expenses when paid.",
      accrual: "Accrual: income counts when earned and expenses when incurred, whether or not money has changed hands.",
      other: "Another method the IRS permits, such as a hybrid of cash and accrual.",
    },
    home_office_method: {
      simplified: "Simplified method: $5 per square foot, up to 300 square feet. The engine figures the deduction from the square footage.",
      actual: "Actual expenses, figured on Form 8829. Enter the result on line 30.",
    },
    line_32_at_risk: {
      a: "32a. All of your investment is at risk (you are personally liable for it).",
      b: "32b. Some investment is not at risk, such as nonrecourse financing. The engine sends the loss to Form 6198 to limit it.",
    },
    line_33_inventory_method: {
      cost: "Inventory valued at cost.",
      lcm: "Inventory valued at the lower of cost or market.",
      other: "Another permitted valuation method (explanation required on the form).",
    },
  },
};
