import { type NodeDoc, Topic } from "../../doc.ts";

export const doc: NodeDoc = {
  title: "Form W-2",
  subtitle: "Wage and Tax Statement",
  topic: Topic.Wages,
  summary:
    "The statement each employer sends by January 31 showing an employee's pay and the taxes withheld from it. " +
    "Box 1 wages flow to Form 1040 line 1a and box 2 withholding to line 25a; Social Security and Medicare boxes feed " +
    "Additional Medicare Tax (Form 8959), and box 12 codes drive retirement, HSA and other benefit rules. " +
    "Enter one W-2 per employer, per person.",
  fields: {
    employer_ein: "Box b. The employer's federal identification number (XX-XXXXXXX).",
    employer_name: "Box c. The employer's legal name.",
    employer_address_line1: "Box c. Employer street address.",
    employer_address_line2: "Box c. Second address line, if any.",
    employer_address_city: "Box c. Employer city.",
    employer_address_state: "Box c. Employer state, as a two-letter code.",
    employer_address_zip: "Box c. Employer ZIP code.",
    employee_ssn: "Box a. The employee's SSN. On a joint return, it identifies whether this W-2 is the taxpayer's or the spouse's.",
    box1_wages: "Box 1. Taxable wages, tips and other pay for federal income tax. Goes to Form 1040 line 1a.",
    box2_fed_withheld: "Box 2. Federal income tax the employer withheld. Counts as a payment on Form 1040 line 25a.",
    box3_ss_wages: "Box 3. Wages subject to Social Security tax, up to the annual wage base.",
    box4_ss_withheld: "Box 4. Social Security tax withheld. With two or more employers, the excess over the maximum is refundable on Schedule 3.",
    box5_medicare_wages: "Box 5. Wages and tips subject to Medicare tax (no cap). Used by Form 8959 for Additional Medicare Tax.",
    box6_medicare_withheld: "Box 6. Medicare tax withheld, including any Additional Medicare Tax the employer withheld.",
    box7_ss_tips: "Box 7. Tips you reported to the employer that are subject to Social Security tax.",
    box8_allocated_tips: "Box 8. Tips the employer allocated to you but that you didn't report to them. Taxed through Form 4137.",
    box10_dep_care: "Box 10. Dependent care benefits paid by the employer. Form 2441 figures how much is tax-free.",
    box11_nonqual_plans: "Box 11. Distributions from a nonqualified deferred compensation plan. Already included in box 1.",
    box12_entries: "Box 12. Up to four coded amounts for benefits and deferrals, such as 401(k) contributions (D) or employer HSA contributions (W).",
    "box12_entries.code": "The letter code printed in box 12.",
    "box12_entries.amount": "The dollar amount next to the code.",
    box13_statutory_employee: "Box 13. Statutory employee. These wages go on Schedule C instead of line 1a, so expenses can be deducted.",
    box13_retirement_plan: "Box 13. Covered by a workplace retirement plan. Can limit the traditional IRA deduction.",
    box13_third_party_sick: "Box 13. Sick pay paid by a third party, such as an insurer.",
    box14_entries: "Box 14. Other items the employer chose to report, such as state disability insurance or union dues.",
    "box14_entries.description": "The label the employer printed.",
    "box14_entries.amount": "The dollar amount.",
    "box14_entries.is_state_sdi_pfml": "Mark if this is state disability (SDI) or paid family leave (PFML) tax, which can be deducted as a state tax on Schedule A.",
    box14b_tipped_code: "The three-digit Treasury tipped occupation code, used for the qualified tips deduction.",
    box15_state: "Box 15. The state these state wages relate to.",
    box16_state_wages: "Box 16. Wages subject to state income tax.",
    box17_state_withheld: "Box 17. State income tax withheld. Can be deducted as a state tax on Schedule A.",
    box18_local_wages: "Box 18. Wages subject to local income tax.",
    box19_local_withheld: "Box 19. Local income tax withheld. Can be deducted on Schedule A.",
    taxpayer_age: "The employee's age, used to apply the higher catch-up limits for retirement plan deferrals at 50 and older.",
  },
  options: {
    "box12_entries.code": {
      A: "Uncollected Social Security tax on tips",
      AA: "Designated Roth contributions to a 401(k)",
      B: "Uncollected Medicare tax on tips",
      BB: "Designated Roth contributions to a 403(b)",
      C: "Taxable cost of group-term life insurance over $50,000",
      D: "Elective deferrals to a 401(k)",
      DD: "Cost of employer-sponsored health coverage (not taxable)",
      E: "Elective deferrals to a 403(b)",
      EE: "Designated Roth contributions to a governmental 457(b)",
      F: "Elective deferrals to a SARSEP",
      FF: "Benefits under a qualified small employer HRA",
      G: "Deferrals and employer contributions to a 457(b)",
      GG: "Income from qualified equity grants (section 83(i))",
      H: "Deferrals to a 501(c)(18)(D) plan",
      HH: "Aggregate deferrals under section 83(i) elections",
      J: "Nontaxable sick pay",
      K: "20% excise tax on excess golden parachute payments",
      L: "Substantiated employee business expense reimbursements",
      M: "Uncollected Social Security tax on group-term life insurance",
      N: "Uncollected Medicare tax on group-term life insurance",
      P: "Excludable moving expense reimbursements (armed forces)",
      Q: "Nontaxable combat pay",
      R: "Employer contributions to an Archer MSA",
      S: "Salary reduction contributions to a SIMPLE plan",
      T: "Employer-provided adoption benefits",
      V: "Income from exercising nonstatutory stock options",
      W: "Employer and pre-tax employee contributions to an HSA",
      Y: "Deferrals under a section 409A nonqualified plan",
      Z: "Income from a nonqualified plan that fails section 409A",
    },
  },
};
