import { type NodeDoc, Topic } from "../../doc.ts";

export const doc: NodeDoc = {
  title: "Schedule K-1 (Form 1065)",
  subtitle: "Partner's Share of Income, Deductions, Credits, etc.",
  topic: Topic.PassThrough,
  summary:
    "The statement a partnership (or an LLC taxed as one) gives each partner showing their share of its income, deductions and credits. " +
    "Business, rental, royalty and guaranteed payment income go through Schedule E to Schedule 1 line 5; interest and dividends to Schedule B; capital gains to Schedule D. " +
    "Self-employment earnings go to Schedule SE, qualified business income to Form 8995, and passive income to Form 8960. Enter one K-1 per partnership.",
  fields: {
    partnership_name: "The name of the partnership. Used as the payer name on Schedule B.",
    partnership_ein: "The partnership's employer identification number.",
    box1_ordinary_business: "Box 1. Ordinary business income or loss. Reported on Schedule E and carried to Schedule 1 line 5. Treated as passive investment income on Form 8960 when no self-employment earnings are reported.",
    box2_rental_re: "Box 2. Net rental real estate income or loss. Reported on Schedule E, carried to Schedule 1 line 5, and counted on Form 8960.",
    box3_other_rental: "Box 3. Other net rental income or loss. Reported on Schedule E, carried to Schedule 1 line 5, and counted on Form 8960.",
    box4a_guaranteed_services: "Box 4a. Guaranteed payments for services you performed. Reported on Schedule E and, if box 14a is blank, used as self-employment earnings on Schedule SE.",
    box4b_guaranteed_capital: "Box 4b. Guaranteed payments for the use of your capital. Reported on Schedule E; not self-employment income.",
    box4c_total_guaranteed_payments: "Box 4c. Total guaranteed payments (4a plus 4b). For reference; the engine uses 4a and 4b.",
    box5_interest: "Box 5. Interest income. Listed on Schedule B, Part I.",
    box6a_ordinary_dividends: "Box 6a. Ordinary dividends. Listed on Schedule B, Part II, and counted as investment income on Form 8960.",
    box6b_qualified_dividends: "Box 6b. Qualified dividends, taxed at capital gain rates. Goes to Form 1040 line 3a.",
    box6c_dividend_equivalents: "Box 6c. Dividend equivalents (substitute dividend payments under section 871(m)). Listed on Schedule B as ordinary dividends.",
    box7_royalties: "Box 7. Royalties. Reported on Schedule E, carried to Schedule 1 line 5, and counted on Form 8960.",
    box8_net_st_cap_gain: "Box 8. Net short-term capital gain or loss. Goes to Schedule D line 5.",
    box9a_net_lt_cap_gain: "Box 9a. Net long-term capital gain or loss. Goes to Schedule D line 12.",
    box9b_collectibles_gain: "Box 9b. Collectibles (28%) gain or loss. Sent to the 28% Rate Gain Worksheet.",
    box9c_unrecaptured_1250: "Box 9c. Unrecaptured section 1250 gain, taxed at up to 25%. Sent to the Unrecaptured Section 1250 Gain Worksheet.",
    box9b_unrecaptured_1250: "Older field for unrecaptured section 1250 gain, from before the box was renumbered 9c. Added to box 9c.",
    box10_net_1231: "Box 10. Net section 1231 gain or loss from business property. Goes to Form 4797, Part I.",
    box11_other_income: "Box 11. Other income or loss. The engine reports the total on Schedule 1 line 8z.",
    box12_section_179: "Box 12. Your share of the section 179 expense deduction. Sent to Form 4562, where your own limits apply.",
    box14a_se_earnings: "Box 14, code A. Net earnings from self-employment. Goes to Schedule SE, taking priority over box 4a.",
    box16_foreign_tax: "Foreign taxes paid or accrued on your share of income (now detailed on Schedule K-3). With foreign income and a category, sent to Form 1116.",
    box16_foreign_income: "Gross foreign-source income tied to the foreign taxes. Needed for the Form 1116 limit.",
    box16_foreign_income_category: "The foreign tax credit category (basket) the foreign income belongs to on Form 1116.",
    box16_foreign_deductions: "Deductions directly allocable to the foreign income. Reduces foreign income on Form 1116.",
    box18_tax_exempt_income: "Box 18. Tax-exempt income and nondeductible expenses. These affect your basis but are not taxed, so the engine does not route them.",
    box19_distributions: "Box 19. Cash and property the partnership distributed to you. Not taxed while within your basis; not routed by the engine.",
    box20z_qbi: "Box 20, code Z. Your qualified business income or loss for the section 199A deduction. Goes to Form 8995.",
    box20_w2_wages: "Box 20, code Z. W-2 wages paid by the business, used in the QBI wage limitation. Goes to Form 8995.",
    box20_ubia: "Box 20, code Z. Unadjusted basis immediately after acquisition of qualified property (UBIA). Recorded; not currently passed on by the engine.",
    box20_sstb: "Mark if the business is a specified service trade or business. Recorded; not currently used by the engine.",
    box20_aggregation_group: "Name of the QBI aggregation group this business belongs to, if you aggregate businesses. Recorded; not currently used by the engine.",
    box13_deductions: "Box 13. Other deductions, such as charitable contributions or investment interest, as one net amount. Not routed here; enter these items where they belong (for example Schedule A).",
    box17_amt_adjustment: "Box 17. Alternative minimum tax adjustments and preferences. The net amount goes to Form 6251.",
    basis_beginning: "Partner basis worksheet. Your outside basis in the partnership at the start of the year. Recorded; basis limits are not yet applied by the engine.",
    basis_contributions: "Partner basis worksheet. Cash and property you contributed during the year, which increases basis.",
    basis_share_of_income: "Partner basis worksheet. Your share of partnership income, which increases basis.",
    basis_share_of_losses: "Partner basis worksheet. Your share of partnership losses and deductions, entered as a positive number; reduces basis.",
    basis_distributions: "Partner basis worksheet. Distributions you received, entered as a positive number; reduces basis.",
    basis_liabilities_assumed: "Partner basis worksheet. Increase in your share of partnership liabilities, which increases basis.",
    basis_liabilities_relieved: "Partner basis worksheet. Decrease in your share of partnership liabilities, which reduces basis.",
    pre2018_basis_ordinary_loss: "Ordinary losses from years before 2018 suspended because you lacked basis. Recorded only.",
    pre2018_basis_st_cap_loss: "Short-term capital losses from years before 2018 suspended because you lacked basis. Recorded only.",
    pre2018_basis_lt_cap_loss: "Long-term capital losses from years before 2018 suspended because you lacked basis. Recorded only.",
    pre2018_basis_other_loss: "Other losses from years before 2018 suspended because you lacked basis. Recorded only.",
    pre2018_atrisk_ordinary_loss: "Ordinary losses from years before 2018 suspended under the at-risk rules. Recorded only.",
    pre2018_atrisk_st_cap_loss: "Short-term capital losses from years before 2018 suspended under the at-risk rules. Recorded only.",
    pre2018_atrisk_lt_cap_loss: "Long-term capital losses from years before 2018 suspended under the at-risk rules. Recorded only.",
    pre2018_atrisk_other_loss: "Other losses from years before 2018 suspended under the at-risk rules. Recorded only.",
  },
  options: {
    box16_foreign_income_category: {
      passive: "Passive category income, such as most interest, dividends, rents and royalties.",
      general: "General category income, such as wages and active business income.",
      section_951a: "Global intangible low-taxed income (GILTI) under section 951A.",
      branch: "Foreign branch category income.",
      treaty: "Income re-sourced as foreign under a tax treaty.",
      section_901j: "Income from sanctioned countries under section 901(j).",
    },
  },
};
