import { type NodeDoc, Topic } from "../../doc.ts";

export const doc: NodeDoc = {
  title: "Schedule E",
  subtitle: "Supplemental Income and Loss (Part I: rental real estate and royalties)",
  topic: Topic.PassThrough,
  summary:
    "The schedule you file to report income and expenses from rental real estate and royalties. Enter one entry per property. " +
    "The engine nets each property's rents and royalties against its expenses, applies the vacation home rules, and sends the total to " +
    "Schedule 1 line 5 and on to Form 1040 line 8. Passive rental losses are held back and sent to Form 8582, which decides how much you can deduct this year; " +
    "other entries feed the at-risk rules (Form 6198), net investment income tax (Form 8960), the QBI deduction and AMT.",
  fields: {
    tsj: "Whose property this is: the taxpayer's, the spouse's, or jointly owned.",
    property_description: "Line 1a. A short description of the property, such as its street address or \"oil royalty, Smith lease\".",
    property_type: "Line 1b. The property type code: 1 single family residence, 2 multi-family residence, 3 vacation or short-term rental, 4 commercial, 5 land, 6 royalties, 7 self-rental, 8 other (describe it below).",
    activity_type: "How the engine treats this activity under the passive activity rules. Types A and B are passive and their losses go through Form 8582; C and D are not.",
    fair_rental_days: "Line 2. Days during the year the property was rented at a fair rental price. If fewer than 15, the engine treats the rental as not reportable: no income and no deductions.",
    personal_use_days: "Line 2. Days you, your family or anyone paying less than fair rent used the property. More than 14 days, or more than 10% of the fair rental days, makes it a vacation home and the engine won't let it show a loss.",
    rent_income: "Line 3. Rents received for the property, including any rents reported to you on Form 1099-MISC or 1099-K.",
    form_1099_payments_made: "Line A. Whether you made payments this year that would require you to file Forms 1099, such as to a contractor.",
    form_1099_filed: "Line B. If line A is yes, whether you filed or will file all required Forms 1099. Required when line A is yes.",
    property_type_other_desc: "Line 1b. A description of the property when you chose type 8 (other). Required for that type.",
    street_address: "Line 1a. Street address of the property.",
    city: "Line 1a. City of the property.",
    state: "Line 1a. State of the property.",
    zip: "Line 1a. ZIP code of the property.",
    foreign_country: "Line 1a. The country, for a property outside the United States.",
    qualified_joint_venture: "Line 2. Check if you and your spouse file jointly, both materially participate, and elect to treat the rental as a qualified joint venture. Recorded for the form; the engine does not compute with it.",
    some_investment_not_at_risk: "Check if some of your investment in this activity is not at risk, such as nonrecourse loans you aren't personally liable for. The engine then sends the activity to Form 6198.",
    operating_expenses_carryover: "Operating expenses from a prior year that the vacation home rules didn't let you deduct, carried forward. The engine adds them to this year's expenses.",
    ownership_percent: "Your ownership share of the property, as a percentage. The engine multiplies income and expenses by it. Leave blank for 100%.",
    tax_court_method: "Check to use the Tax Court method, which allocates mortgage interest and taxes on a vacation home by days in the year rather than days used. Recorded; the engine does not apply this allocation.",
    days_owned_in_year: "The number of days you owned the property, if not the whole year. Used with the Tax Court method; the engine does not compute with it.",
    placed_in_service: "Check if the property was first placed in service as a rental this year. Informational.",
    disposed_of: "Check if you sold or otherwise disposed of the property this year. The engine flags the disposition for Form 4797, where gain or loss on business property is reported.",
    carry_to_8960: "Check to include this property's net income or loss on Form 8960 line 4b for the net investment income tax.",
    main_home_or_second_home: "Check if you also used this property as your main or second home, such as a duplex where you live in one unit. With an occupancy percentage, the personal share of mortgage interest and taxes goes to Schedule A.",
    occupancy_percent: "The percentage of the property you or your spouse occupied. The engine sends that share of this property's mortgage interest and real estate taxes to Schedule A lines 8a and 5b.",
    prior_unallowed_passive_operating: "Passive operating losses from this activity that Form 8582 didn't allow in earlier years, carried forward. Used for passive types A and B.",
    prior_unallowed_passive_4797_part1: "Prior-year passive losses from Form 4797 Part I (sales of business property) for this activity that were suspended, carried forward.",
    prior_unallowed_passive_4797_part2: "Prior-year passive losses from Form 4797 Part II (ordinary gains and losses) for this activity that were suspended, carried forward.",
    prior_unallowed_at_risk: "Losses from this activity that the at-risk rules (Form 6198) didn't allow in earlier years. The engine sends them to Form 6198.",
    disallowed_mortgage_interest_8990: "Mortgage interest from this activity that Form 8990 didn't allow last year under the business interest limit, carried forward to Form 8990.",
    disallowed_other_interest_8990: "Other interest from this activity that Form 8990 didn't allow last year under the business interest limit, carried forward to Form 8990.",
    qbi_trade_or_business: "Whether this rental rises to the level of a trade or business (or meets the rental safe harbor), so its income counts for the qualified business income deduction on Form 8995.",
    qbi_specified_service: "Check if the activity is a specified service trade or business for the QBI deduction, which can limit the deduction at higher incomes.",
    qbi_aggregation_number: "A number grouping this activity with others you aggregate as one trade or business for the QBI deduction. Recorded; the engine does not aggregate by it.",
    qbi_w2_wages: "W-2 wages paid by this activity, used for the wage limit on the QBI deduction at higher incomes.",
    qbi_unadjusted_basis: "Unadjusted basis immediately after acquisition (UBIA) of the activity's qualified property, used with W-2 wages for the QBI deduction limit.",
    qbi_override: "An amount to use as this activity's qualified business income instead of its computed net income.",
    qbi_safe_harbor: "Which version of the Rev. Proc. 2019-38 rental real estate safe harbor you use to treat the rental as a trade or business. Recorded; the engine does not test the safe harbor.",
    section_179: "Section 179 expense you elect for property used in this activity. The engine passes it to Form 4562 only for activity type C (real estate professional).",
    section_1231_gain_loss: "Gain (positive) or loss (negative) on disposing of the property under section 1231. Recorded; the engine does not compute with it here.",
    elect_out_biie: "Check if you elect out of the business interest expense limit as a real property trade or business. Recorded; the engine does not compute with it.",
    royalties_income: "Line 4. Royalties received, such as from oil, gas, mineral, copyright or patent rights.",
    expense_advertising: "Line 5. Advertising.",
    expense_auto_travel: "Line 6. Auto and travel expenses for the rental. Amounts from the vehicle expense worksheet are added here.",
    expense_cleaning: "Line 7. Cleaning and maintenance.",
    expense_commissions: "Line 8. Commissions, such as to a rental agent.",
    expense_insurance: "Line 9. Insurance.",
    expense_legal_professional: "Line 10. Legal and other professional fees.",
    expense_management: "Line 11. Management fees.",
    expense_mortgage_interest: "Line 12. Mortgage interest paid to banks and others, such as on Form 1098.",
    expense_other_interest: "Line 13. Other interest.",
    expense_repairs: "Line 14. Repairs.",
    expense_supplies: "Line 15. Supplies.",
    expense_taxes: "Line 16. Taxes, such as real estate taxes on the property.",
    expense_utilities: "Line 17. Utilities.",
    expense_depreciation: "Line 18. Depreciation (usually from Form 4562) for the regular tax.",
    expense_depreciation_amt: "The difference between regular tax and alternative minimum tax depreciation for this property. The engine sends it to Form 6251 as an AMT adjustment.",
    expense_depletion: "Line 18. Depletion, such as on royalty property. Amounts from the depletion worksheet are added here.",
    expense_other_lines: "Line 19. Other expenses not listed above, up to six items.",
    "expense_other_lines.description": "What the expense is.",
    "expense_other_lines.amount": "The amount of the expense.",
  },
  options: {
    tsj: {
      T: "Taxpayer",
      S: "Spouse",
      J: "Joint (owned by both)",
    },
    activity_type: {
      A: "Rental real estate you actively participate in. Passive, but losses can qualify for the special allowance on Form 8582.",
      B: "Other passive activity. Losses can only offset passive income.",
      C: "Rental real estate of a qualifying real estate professional. Not passive.",
      D: "Other nonpassive activity, such as a royalty you hold directly.",
    },
    qbi_trade_or_business: {
      Y: "Yes, the activity is a trade or business for the QBI deduction.",
      N: "No, the activity does not qualify for the QBI deduction.",
    },
    qbi_safe_harbor: {
      A: "Each property treated as a separate rental enterprise.",
      B: "All residential properties grouped as one enterprise.",
      C: "All commercial properties grouped as one enterprise.",
    },
  },
};
